// Code generated by go-swagger; DO NOT EDIT.

package cat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteCatOKCode is the HTTP code returned for type DeleteCatOK
const DeleteCatOKCode int = 200

/*DeleteCatOK OK

swagger:response deleteCatOK
*/
type DeleteCatOK struct {
}

// NewDeleteCatOK creates DeleteCatOK with default headers values
func NewDeleteCatOK() *DeleteCatOK {

	return &DeleteCatOK{}
}

// WriteResponse to the client
func (o *DeleteCatOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteCatNoContentCode is the HTTP code returned for type DeleteCatNoContent
const DeleteCatNoContentCode int = 204

/*DeleteCatNoContent Deleted

swagger:response deleteCatNoContent
*/
type DeleteCatNoContent struct {
}

// NewDeleteCatNoContent creates DeleteCatNoContent with default headers values
func NewDeleteCatNoContent() *DeleteCatNoContent {

	return &DeleteCatNoContent{}
}

// WriteResponse to the client
func (o *DeleteCatNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteCatBadRequestCode is the HTTP code returned for type DeleteCatBadRequest
const DeleteCatBadRequestCode int = 400

/*DeleteCatBadRequest Bad Request

swagger:response deleteCatBadRequest
*/
type DeleteCatBadRequest struct {
}

// NewDeleteCatBadRequest creates DeleteCatBadRequest with default headers values
func NewDeleteCatBadRequest() *DeleteCatBadRequest {

	return &DeleteCatBadRequest{}
}

// WriteResponse to the client
func (o *DeleteCatBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteCatInternalServerErrorCode is the HTTP code returned for type DeleteCatInternalServerError
const DeleteCatInternalServerErrorCode int = 500

/*DeleteCatInternalServerError Internal Server Error

swagger:response deleteCatInternalServerError
*/
type DeleteCatInternalServerError struct {
}

// NewDeleteCatInternalServerError creates DeleteCatInternalServerError with default headers values
func NewDeleteCatInternalServerError() *DeleteCatInternalServerError {

	return &DeleteCatInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteCatInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
