// Code generated by go-swagger; DO NOT EDIT.

package cat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/pk80/student/transactions/models"
)

// NewDeleteBulkParams creates a new DeleteBulkParams object
// no default values defined in spec.
func NewDeleteBulkParams() DeleteBulkParams {

	return DeleteBulkParams{}
}

// DeleteBulkParams contains all the bound params for the delete bulk operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteBulk
type DeleteBulkParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	CatList models.CatList
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteBulkParams() beforehand.
func (o *DeleteBulkParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.CatList
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("catList", "body"))
			} else {
				res = append(res, errors.NewParseError("catList", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.CatList = body
			}
		}
	} else {
		res = append(res, errors.Required("catList", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
