// Code generated by go-swagger; DO NOT EDIT.

package cat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/pk80/student/transactions/models"
)

// GetBulkCatOKCode is the HTTP code returned for type GetBulkCatOK
const GetBulkCatOKCode int = 200

/*GetBulkCatOK OK

swagger:response getBulkCatOK
*/
type GetBulkCatOK struct {

	/*
	  In: Body
	*/
	Payload models.CatData `json:"body,omitempty"`
}

// NewGetBulkCatOK creates GetBulkCatOK with default headers values
func NewGetBulkCatOK() *GetBulkCatOK {

	return &GetBulkCatOK{}
}

// WithPayload adds the payload to the get bulk cat o k response
func (o *GetBulkCatOK) WithPayload(payload models.CatData) *GetBulkCatOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bulk cat o k response
func (o *GetBulkCatOK) SetPayload(payload models.CatData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBulkCatOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.CatData{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetBulkCatInternalServerErrorCode is the HTTP code returned for type GetBulkCatInternalServerError
const GetBulkCatInternalServerErrorCode int = 500

/*GetBulkCatInternalServerError Internal Server Error

swagger:response getBulkCatInternalServerError
*/
type GetBulkCatInternalServerError struct {
}

// NewGetBulkCatInternalServerError creates GetBulkCatInternalServerError with default headers values
func NewGetBulkCatInternalServerError() *GetBulkCatInternalServerError {

	return &GetBulkCatInternalServerError{}
}

// WriteResponse to the client
func (o *GetBulkCatInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
