// Code generated by go-swagger; DO NOT EDIT.

package cat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/pk80/student/transactions/models"
)

// GetCatOKCode is the HTTP code returned for type GetCatOK
const GetCatOKCode int = 200

/*GetCatOK OK

swagger:response getCatOK
*/
type GetCatOK struct {

	/*
	  In: Body
	*/
	Payload *models.Cat `json:"body,omitempty"`
}

// NewGetCatOK creates GetCatOK with default headers values
func NewGetCatOK() *GetCatOK {

	return &GetCatOK{}
}

// WithPayload adds the payload to the get cat o k response
func (o *GetCatOK) WithPayload(payload *models.Cat) *GetCatOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cat o k response
func (o *GetCatOK) SetPayload(payload *models.Cat) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCatOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCatBadRequestCode is the HTTP code returned for type GetCatBadRequest
const GetCatBadRequestCode int = 400

/*GetCatBadRequest Bad Request

swagger:response getCatBadRequest
*/
type GetCatBadRequest struct {
}

// NewGetCatBadRequest creates GetCatBadRequest with default headers values
func NewGetCatBadRequest() *GetCatBadRequest {

	return &GetCatBadRequest{}
}

// WriteResponse to the client
func (o *GetCatBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetCatNotFoundCode is the HTTP code returned for type GetCatNotFound
const GetCatNotFoundCode int = 404

/*GetCatNotFound Not found

swagger:response getCatNotFound
*/
type GetCatNotFound struct {
}

// NewGetCatNotFound creates GetCatNotFound with default headers values
func NewGetCatNotFound() *GetCatNotFound {

	return &GetCatNotFound{}
}

// WriteResponse to the client
func (o *GetCatNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetCatInternalServerErrorCode is the HTTP code returned for type GetCatInternalServerError
const GetCatInternalServerErrorCode int = 500

/*GetCatInternalServerError Internal Server Error

swagger:response getCatInternalServerError
*/
type GetCatInternalServerError struct {
}

// NewGetCatInternalServerError creates GetCatInternalServerError with default headers values
func NewGetCatInternalServerError() *GetCatInternalServerError {

	return &GetCatInternalServerError{}
}

// WriteResponse to the client
func (o *GetCatInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
