// Code generated by go-swagger; DO NOT EDIT.

package cat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCatHandlerFunc turns a function with the right signature into a get cat handler
type GetCatHandlerFunc func(GetCatParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCatHandlerFunc) Handle(params GetCatParams) middleware.Responder {
	return fn(params)
}

// GetCatHandler interface for that can handle valid get cat params
type GetCatHandler interface {
	Handle(GetCatParams) middleware.Responder
}

// NewGetCat creates a new http.Handler for the get cat operation
func NewGetCat(ctx *middleware.Context, handler GetCatHandler) *GetCat {
	return &GetCat{Context: ctx, Handler: handler}
}

/*GetCat swagger:route GET /cat/{id} cat getCat

Get single Category record details by matching `id`

*/
type GetCat struct {
	Context *middleware.Context
	Handler GetCatHandler
}

func (o *GetCat) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCatParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
