// Code generated by go-swagger; DO NOT EDIT.

package cat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ImportCatHandlerFunc turns a function with the right signature into a import cat handler
type ImportCatHandlerFunc func(ImportCatParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ImportCatHandlerFunc) Handle(params ImportCatParams) middleware.Responder {
	return fn(params)
}

// ImportCatHandler interface for that can handle valid import cat params
type ImportCatHandler interface {
	Handle(ImportCatParams) middleware.Responder
}

// NewImportCat creates a new http.Handler for the import cat operation
func NewImportCat(ctx *middleware.Context, handler ImportCatHandler) *ImportCat {
	return &ImportCat{Context: ctx, Handler: handler}
}

/*ImportCat swagger:route POST /cat/ cat importCat

Upload categories file in csv format and append to `catFileList` and post `cat` into `catData`

*/
type ImportCat struct {
	Context *middleware.Context
	Handler ImportCatHandler
}

func (o *ImportCat) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewImportCatParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
