// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// SuccessMsg success msg
// swagger:model successMsg
type SuccessMsg string

// Validate validates this success msg
func (m SuccessMsg) Validate(formats strfmt.Registry) error {
	return nil
}
