// Code generated by go-swagger; DO NOT EDIT.

package bofa_chk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// BofaChkUpdateHandlerFunc turns a function with the right signature into a bofa chk update handler
type BofaChkUpdateHandlerFunc func(BofaChkUpdateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn BofaChkUpdateHandlerFunc) Handle(params BofaChkUpdateParams) middleware.Responder {
	return fn(params)
}

// BofaChkUpdateHandler interface for that can handle valid bofa chk update params
type BofaChkUpdateHandler interface {
	Handle(BofaChkUpdateParams) middleware.Responder
}

// NewBofaChkUpdate creates a new http.Handler for the bofa chk update operation
func NewBofaChkUpdate(ctx *middleware.Context, handler BofaChkUpdateHandler) *BofaChkUpdate {
	return &BofaChkUpdate{Context: ctx, Handler: handler}
}

/*BofaChkUpdate swagger:route PUT /tx/bofa-chk/ bofa-chk bofaChkUpdate

Update transaction details for bofa-chk by uploading a file by referencing to `lastId`

*/
type BofaChkUpdate struct {
	Context *middleware.Context
	Handler BofaChkUpdateHandler
}

func (o *BofaChkUpdate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewBofaChkUpdateParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
