// Code generated by go-swagger; DO NOT EDIT.

package bofa_chk

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/pk80/student/transactions/models"
)

// BofaChkImportOKCode is the HTTP code returned for type BofaChkImportOK
const BofaChkImportOKCode int = 200

/*BofaChkImportOK OK

swagger:response bofaChkImportOK
*/
type BofaChkImportOK struct {

	/*
	  In: Body
	*/
	Payload models.TxData `json:"body,omitempty"`
}

// NewBofaChkImportOK creates BofaChkImportOK with default headers values
func NewBofaChkImportOK() *BofaChkImportOK {

	return &BofaChkImportOK{}
}

// WithPayload adds the payload to the bofa chk import o k response
func (o *BofaChkImportOK) WithPayload(payload models.TxData) *BofaChkImportOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the bofa chk import o k response
func (o *BofaChkImportOK) SetPayload(payload models.TxData) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BofaChkImportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.TxData{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// BofaChkImportInternalServerErrorCode is the HTTP code returned for type BofaChkImportInternalServerError
const BofaChkImportInternalServerErrorCode int = 500

/*BofaChkImportInternalServerError Internal Server Error

swagger:response bofaChkImportInternalServerError
*/
type BofaChkImportInternalServerError struct {
}

// NewBofaChkImportInternalServerError creates BofaChkImportInternalServerError with default headers values
func NewBofaChkImportInternalServerError() *BofaChkImportInternalServerError {

	return &BofaChkImportInternalServerError{}
}

// WriteResponse to the client
func (o *BofaChkImportInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
