// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/pk80/student/swagAPI/models"
)

// GetCustomerOKCode is the HTTP code returned for type GetCustomerOK
const GetCustomerOKCode int = 200

/*GetCustomerOK Customer found

swagger:response getCustomerOK
*/
type GetCustomerOK struct {
}

// NewGetCustomerOK creates GetCustomerOK with default headers values
func NewGetCustomerOK() *GetCustomerOK {

	return &GetCustomerOK{}
}

// WriteResponse to the client
func (o *GetCustomerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetCustomerNotFoundCode is the HTTP code returned for type GetCustomerNotFound
const GetCustomerNotFoundCode int = 404

/*GetCustomerNotFound Customer not found

swagger:response getCustomerNotFound
*/
type GetCustomerNotFound struct {
}

// NewGetCustomerNotFound creates GetCustomerNotFound with default headers values
func NewGetCustomerNotFound() *GetCustomerNotFound {

	return &GetCustomerNotFound{}
}

// WriteResponse to the client
func (o *GetCustomerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

/*GetCustomerDefault error

swagger:response getCustomerDefault
*/
type GetCustomerDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCustomerDefault creates GetCustomerDefault with default headers values
func NewGetCustomerDefault(code int) *GetCustomerDefault {
	if code <= 0 {
		code = 500
	}

	return &GetCustomerDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get customer default response
func (o *GetCustomerDefault) WithStatusCode(code int) *GetCustomerDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get customer default response
func (o *GetCustomerDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get customer default response
func (o *GetCustomerDefault) WithPayload(payload *models.Error) *GetCustomerDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get customer default response
func (o *GetCustomerDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCustomerDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
