// Code generated by go-swagger; DO NOT EDIT.

package tx

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteParams creates a new DeleteParams object
// no default values defined in spec.
func NewDeleteParams() DeleteParams {

	return DeleteParams{}
}

// DeleteParams contains all the bound params for the delete operation
// typically these are obtained from a http.Request
//
// swagger:parameters delete
type DeleteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  Pattern: ^([0-9]{4})([0])([123456789])|([0-9]{4})([1])([12])$
	  In: query
	*/
	Month string
	/*
	  Required: true
	  In: query
	*/
	Source string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteParams() beforehand.
func (o *DeleteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qMonth, qhkMonth, _ := qs.GetOK("month")
	if err := o.bindMonth(qMonth, qhkMonth, route.Formats); err != nil {
		res = append(res, err)
	}

	qSource, qhkSource, _ := qs.GetOK("source")
	if err := o.bindSource(qSource, qhkSource, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindMonth binds and validates parameter Month from query.
func (o *DeleteParams) bindMonth(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("month", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("month", "query", raw); err != nil {
		return err
	}

	o.Month = raw

	if err := o.validateMonth(formats); err != nil {
		return err
	}

	return nil
}

// validateMonth carries on validations for parameter Month
func (o *DeleteParams) validateMonth(formats strfmt.Registry) error {

	if err := validate.Pattern("month", "query", o.Month, `^([0-9]{4})([0])([123456789])|([0-9]{4})([1])([12])$`); err != nil {
		return err
	}

	return nil
}

// bindSource binds and validates parameter Source from query.
func (o *DeleteParams) bindSource(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("source", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("source", "query", raw); err != nil {
		return err
	}

	o.Source = raw

	return nil
}
