// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Fetching customer information",
    "title": "Customers",
    "version": "0.0.1"
  },
  "paths": {
    "/customer": {
      "post": {
        "operationId": "postCustomer",
        "parameters": [
          {
            "description": "customer to be created",
            "name": "customer",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/customer"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Customer created"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/customer/{email}": {
      "get": {
        "description": "customer to be found",
        "operationId": "getCustomer",
        "parameters": [
          {
            "pattern": "[a-z0-9._%+-]+@[a-z0-9.-]+\\.com$",
            "type": "string",
            "format": "email",
            "description": "email of the customer",
            "name": "email",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Customer found"
          },
          "404": {
            "description": "Customer not found"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "customer": {
      "properties": {
        "cname": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "id": {
          "type": "integer"
        },
        "status": {
          "type": "string",
          "enum": [
            "Active",
            "Inactive",
            "Deleted"
          ]
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Fetching customer information",
    "title": "Customers",
    "version": "0.0.1"
  },
  "paths": {
    "/customer": {
      "post": {
        "operationId": "postCustomer",
        "parameters": [
          {
            "description": "customer to be created",
            "name": "customer",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/customer"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Customer created"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/customer/{email}": {
      "get": {
        "description": "customer to be found",
        "operationId": "getCustomer",
        "parameters": [
          {
            "pattern": "[a-z0-9._%+-]+@[a-z0-9.-]+\\.com$",
            "type": "string",
            "format": "email",
            "description": "email of the customer",
            "name": "email",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Customer found"
          },
          "404": {
            "description": "Customer not found"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "customer": {
      "properties": {
        "cname": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "id": {
          "type": "integer"
        },
        "status": {
          "type": "string",
          "enum": [
            "Active",
            "Inactive",
            "Deleted"
          ]
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
}
