---
swagger: "2.0"
info:
  title: Customers
  version: "0.0.1"
  description: Fetching customer information #added

# host: localhost:8080
# basePath:  /
schemes:
  - http

consumes:
  - application/json #need a change ?
produces:
  - application/json #need a change ?

definitions:
  customer:
    #type:  object
    properties:
      id:
        type: integer
      cname:
        type: string
      email:
        type: string
        format: email
      status:
        type: string
        enum:
          - Active
          - Inactive
          - Deleted
  error: #added
    type: object
    required:
      - message
    properties:
      code:
        type: integer
      message:
        type: string

paths:
  /customer:
    post:
      # tags:
      #   - postCustomer
      operationId: postCustomer
      parameters:
        - name: customer
          in: body
          description: customer to be created
          schema:
            $ref: '#/definitions/customer'
      responses:
        201:
         description: Customer created
        500:
          description: Internal Server Error
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /customer/{email}:
    get:
      # tags:
      #   - getCustomer
      operationId: getCustomer 
      parameters: 
      - name: email
        in: path
        type: string
        format: email
        pattern: '[a-z0-9._%+-]+@[a-z0-9.-]+\.com$'
        description: email of the customer
        required: true
      description: customer to be found
      responses:
        200:
          description: Customer found
        404:
          description: Customer not found
        default:
          description: error
          schema:
            $ref: "#/definitions/error"