---
swagger: '2.0'
info:
  $ref: './info.yml'
  # version: 1.0.0
  # title: Sample API
  # description: |
  #   A simple API to learn how to write OpenAPI Specification.
  #   This file uses almost every single aspect of the [Open API Specification](https://openapis.org/).  
  #   This API will use JSON.  
  #   JSON looks like this:  

  #   ```JSON
  #   {
  #     "key": "value",
  #     "anotherKey": "anotherValue"
  #   }
  #   ```

schemes: 
  - https
host: localhost:8080
basePath: /sample_api

paths:
  /persons:
    get:
      summary: Gets some persons
      description: Returns a list containing persons with pagging support.
      parameters:
        - name: pageSize
          in: query
          description: Number of persons returned
          type: integer
        - name: pageNumber
          in: query
          description: Page Number
          type: integer
      responses:
        200:
          description: A list of Person
          schema:
            $ref: '#/definitions/Persons'
    post:
      summary: Creates a person
      description: Adds a new person to the person list.
      parameters:
        - name: person
          in: body
          description: The person to create
          schema:
            # $ref: '#/definitions/Person'
            $ref: './person.yml#/Person'
      responses:
        204:
          description: Person succesfully created.
        400:
          description: Personc couldn't have been created.
  /persons/{username}:
    get:
      summary: Gets a person 
      description: Returns a single person for its username.
      parameters:
        - name: username
          in: path
          required: true
          description: The person's username.
          type: string
      responses:
        200:
          description: A person.
          schema:
            # $ref: '#/definitions/Person'
            $ref: './person.yml#/Person'
        404:
          description: The person doesn't exist.

definitions:
  # Person:
  #   required:
  #     - username
  #   properties:
  #     username:
  #       type:  string
  #     firstName:
  #       type: string
  #     lastName:
  #       type: string
  Persons:
    type: array
    items:
      # $ref: '#/definitions/Person'
      $ref: './person.yml#/Person'