// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Transactions
This is a sample api for all sorts of transactions. And all transactions are categorized based upon type of account operation. >>TODO<<

Terms Of Service:

https://www.atlassian.com/legal/cloud-terms-of-service


    Schemes:
      http
    Host: localhost:8080
    BasePath: /
    Version: 0.0.1
    License: License https://user@bitbucket.org
    Contact: Developer<developer@email.com> https://user@bitbucket.org

    Consumes:
    - application/json
    - multipart/form-data

    Produces:
    - application/json

swagger:meta
*/
package restapi
