// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json",
    "multipart/form-data"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a sample api for all sorts of transactions. And all transactions are categorized based upon type of account operation. \u003e\u003eTODO\u003c\u003c",
    "title": "Transactions",
    "termsOfService": "https://www.atlassian.com/legal/cloud-terms-of-service",
    "contact": {
      "name": "Developer",
      "url": "https://user@bitbucket.org",
      "email": "developer@email.com"
    },
    "license": {
      "name": "License",
      "url": "https://user@bitbucket.org"
    },
    "version": "0.0.1"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "paths": {
    "/cat": {
      "delete": {
        "description": "Delete all category related transaction in bulk",
        "tags": [
          "cat"
        ],
        "operationId": "deleteBulk",
        "parameters": [
          {
            "name": "catList",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/catList"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/cat"
            }
          },
          "204": {
            "description": "No Content"
          },
          "206": {
            "description": "Partial Content",
            "schema": {
              "$ref": "#/definitions/cat"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/cat/": {
      "get": {
        "description": "Get all the Category records ` + "`" + `catList` + "`" + ` into the database ` + "`" + `catData` + "`" + `",
        "tags": [
          "cat"
        ],
        "operationId": "getBulkCat",
        "parameters": [
          {
            "name": "catList",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/catList"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/catData"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "description": "Upload categories file in csv format and append to ` + "`" + `catFileList` + "`" + ` and post ` + "`" + `cat` + "`" + ` into ` + "`" + `catData` + "`" + `",
        "tags": [
          "cat"
        ],
        "operationId": "importCat",
        "parameters": [
          {
            "type": "file",
            "format": "text/csv",
            "name": "csvfile",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/catFileList"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/cat/{id}": {
      "get": {
        "description": "Get single Category record details by matching ` + "`" + `id` + "`" + `",
        "tags": [
          "cat"
        ],
        "operationId": "getCat",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/cat"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Not found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "description": "Delete single Category record by matching ` + "`" + `id` + "`" + `",
        "tags": [
          "cat"
        ],
        "operationId": "deleteCat",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "204": {
            "description": "Deleted"
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/tx": {
      "get": {
        "description": "Get transactions for the given ` + "`" + `month` + "`" + `, ` + "`" + `year` + "`" + ` and ` + "`" + `source` + "`" + ` from ` + "`" + `txData` + "`" + `",
        "tags": [
          "tx"
        ],
        "operationId": "getBulk",
        "parameters": [
          {
            "pattern": "^([0-9]{4})([0])([123456789])|([0-9]{4})([1])([12])$",
            "type": "string",
            "name": "month",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "source",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/transactions"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "description": "Delete transactions by ` + "`" + `month` + "`" + `, ` + "`" + `year` + "`" + ` and ` + "`" + `source` + "`" + `",
        "tags": [
          "tx"
        ],
        "operationId": "delete",
        "parameters": [
          {
            "pattern": "^([0-9]{4})([0])([123456789])|([0-9]{4})([1])([12])$",
            "type": "string",
            "name": "month",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "source",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/successMsg"
            }
          },
          "204": {
            "description": "Deleted"
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/tx/bofa-chk/": {
      "put": {
        "description": "Update transaction details for bofa-chk by uploading a file by referencing to ` + "`" + `lastId` + "`" + `",
        "tags": [
          "bofa-chk"
        ],
        "operationId": "bofaChkUpdate",
        "parameters": [
          {
            "type": "file",
            "format": "text/csv",
            "name": "upfile",
            "in": "formData",
            "required": true
          },
          {
            "type": "integer",
            "name": "lastId",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "source",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "description": "Upload transactions for bofa-chk in csv format and append to ` + "`" + `txData` + "`" + `",
        "tags": [
          "bofa-chk"
        ],
        "operationId": "bofaChkImport",
        "parameters": [
          {
            "type": "file",
            "format": "text/csv",
            "name": "csvfile",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/txData"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/tx/{id}": {
      "get": {
        "description": "Get transaction details by matching with ` + "`" + `id` + "`" + `",
        "tags": [
          "tx"
        ],
        "operationId": "get",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/transaction"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    }
  },
  "definitions": {
    "cat": {
      "type": "object",
      "properties": {
        "cat": {
          "type": "string"
        },
        "code": {
          "type": "integer"
        },
        "expFor": {
          "type": "string"
        },
        "frequency": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "auto"
        },
        "possibleTagsStr": {
          "type": "string",
          "format": "binary"
        },
        "subCat": {
          "type": "string"
        },
        "volatility": {
          "type": "string"
        }
      }
    },
    "catData": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/definitions/catList"
          },
          "lastId": {
            "type": "integer"
          },
          "sync": {
            "type": "string"
          }
        }
      }
    },
    "catFile": {
      "type": "object",
      "properties": {
        "cat": {
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "expFor": {
          "type": "string"
        },
        "frequency": {
          "type": "string"
        },
        "possibleTagsStr": {
          "type": "string"
        },
        "subCat": {
          "type": "string"
        },
        "volatility": {
          "type": "string"
        }
      }
    },
    "catFileList": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/catFile"
      }
    },
    "catList": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/cat"
      }
    },
    "successMsg": {
      "type": "string",
      "example": "Operation Successfull"
    },
    "transaction": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "number"
        },
        "date": {
          "type": "string",
          "format": "date"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "notes": {
          "type": "string"
        },
        "source": {
          "type": "string"
        },
        "user": {
          "type": "string"
        }
      }
    },
    "transactions": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/transaction"
      }
    },
    "txData": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/definitions/transaction"
          },
          "lastId": {
            "type": "integer"
          },
          "sync": {
            "type": "string"
          }
        }
      }
    }
  },
  "tags": [
    {
      "description": "All transactions",
      "name": "tx"
    },
    {
      "description": "All BOFA cheque related transactions",
      "name": "bofa-chk"
    },
    {
      "description": "All Categories related to transactions",
      "name": "cat"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json",
    "multipart/form-data"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a sample api for all sorts of transactions. And all transactions are categorized based upon type of account operation. \u003e\u003eTODO\u003c\u003c",
    "title": "Transactions",
    "termsOfService": "https://www.atlassian.com/legal/cloud-terms-of-service",
    "contact": {
      "name": "Developer",
      "url": "https://user@bitbucket.org",
      "email": "developer@email.com"
    },
    "license": {
      "name": "License",
      "url": "https://user@bitbucket.org"
    },
    "version": "0.0.1"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "paths": {
    "/cat": {
      "delete": {
        "description": "Delete all category related transaction in bulk",
        "tags": [
          "cat"
        ],
        "operationId": "deleteBulk",
        "parameters": [
          {
            "name": "catList",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/catList"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/cat"
            }
          },
          "204": {
            "description": "No Content"
          },
          "206": {
            "description": "Partial Content",
            "schema": {
              "$ref": "#/definitions/cat"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/cat/": {
      "get": {
        "description": "Get all the Category records ` + "`" + `catList` + "`" + ` into the database ` + "`" + `catData` + "`" + `",
        "tags": [
          "cat"
        ],
        "operationId": "getBulkCat",
        "parameters": [
          {
            "name": "catList",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/catList"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/catData"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "description": "Upload categories file in csv format and append to ` + "`" + `catFileList` + "`" + ` and post ` + "`" + `cat` + "`" + ` into ` + "`" + `catData` + "`" + `",
        "tags": [
          "cat"
        ],
        "operationId": "importCat",
        "parameters": [
          {
            "type": "file",
            "format": "text/csv",
            "name": "csvfile",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/catFileList"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/cat/{id}": {
      "get": {
        "description": "Get single Category record details by matching ` + "`" + `id` + "`" + `",
        "tags": [
          "cat"
        ],
        "operationId": "getCat",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/cat"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Not found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "description": "Delete single Category record by matching ` + "`" + `id` + "`" + `",
        "tags": [
          "cat"
        ],
        "operationId": "deleteCat",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "204": {
            "description": "Deleted"
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/tx": {
      "get": {
        "description": "Get transactions for the given ` + "`" + `month` + "`" + `, ` + "`" + `year` + "`" + ` and ` + "`" + `source` + "`" + ` from ` + "`" + `txData` + "`" + `",
        "tags": [
          "tx"
        ],
        "operationId": "getBulk",
        "parameters": [
          {
            "pattern": "^([0-9]{4})([0])([123456789])|([0-9]{4})([1])([12])$",
            "type": "string",
            "name": "month",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "source",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/transactions"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "delete": {
        "description": "Delete transactions by ` + "`" + `month` + "`" + `, ` + "`" + `year` + "`" + ` and ` + "`" + `source` + "`" + `",
        "tags": [
          "tx"
        ],
        "operationId": "delete",
        "parameters": [
          {
            "pattern": "^([0-9]{4})([0])([123456789])|([0-9]{4})([1])([12])$",
            "type": "string",
            "name": "month",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "source",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/successMsg"
            }
          },
          "204": {
            "description": "Deleted"
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/tx/bofa-chk/": {
      "put": {
        "description": "Update transaction details for bofa-chk by uploading a file by referencing to ` + "`" + `lastId` + "`" + `",
        "tags": [
          "bofa-chk"
        ],
        "operationId": "bofaChkUpdate",
        "parameters": [
          {
            "type": "file",
            "format": "text/csv",
            "name": "upfile",
            "in": "formData",
            "required": true
          },
          {
            "type": "integer",
            "name": "lastId",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "source",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "description": "Upload transactions for bofa-chk in csv format and append to ` + "`" + `txData` + "`" + `",
        "tags": [
          "bofa-chk"
        ],
        "operationId": "bofaChkImport",
        "parameters": [
          {
            "type": "file",
            "format": "text/csv",
            "name": "csvfile",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/txData"
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/tx/{id}": {
      "get": {
        "description": "Get transaction details by matching with ` + "`" + `id` + "`" + `",
        "tags": [
          "tx"
        ],
        "operationId": "get",
        "parameters": [
          {
            "type": "integer",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/transaction"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    }
  },
  "definitions": {
    "cat": {
      "type": "object",
      "properties": {
        "cat": {
          "type": "string"
        },
        "code": {
          "type": "integer"
        },
        "expFor": {
          "type": "string"
        },
        "frequency": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "auto"
        },
        "possibleTagsStr": {
          "type": "string",
          "format": "binary"
        },
        "subCat": {
          "type": "string"
        },
        "volatility": {
          "type": "string"
        }
      }
    },
    "catData": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/definitions/catList"
          },
          "lastId": {
            "type": "integer"
          },
          "sync": {
            "type": "string"
          }
        }
      }
    },
    "catFile": {
      "type": "object",
      "properties": {
        "cat": {
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "expFor": {
          "type": "string"
        },
        "frequency": {
          "type": "string"
        },
        "possibleTagsStr": {
          "type": "string"
        },
        "subCat": {
          "type": "string"
        },
        "volatility": {
          "type": "string"
        }
      }
    },
    "catFileList": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/catFile"
      }
    },
    "catList": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/cat"
      }
    },
    "successMsg": {
      "type": "string",
      "example": "Operation Successfull"
    },
    "transaction": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "number"
        },
        "date": {
          "type": "string",
          "format": "date"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "notes": {
          "type": "string"
        },
        "source": {
          "type": "string"
        },
        "user": {
          "type": "string"
        }
      }
    },
    "transactions": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/transaction"
      }
    },
    "txData": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/definitions/transaction"
          },
          "lastId": {
            "type": "integer"
          },
          "sync": {
            "type": "string"
          }
        }
      }
    }
  },
  "tags": [
    {
      "description": "All transactions",
      "name": "tx"
    },
    {
      "description": "All BOFA cheque related transactions",
      "name": "bofa-chk"
    },
    {
      "description": "All Categories related to transactions",
      "name": "cat"
    }
  ]
}`))
}
