// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Customer customer
// swagger:model customer
type Customer struct {

	// cname
	Cname string `json:"cname,omitempty"`

	// email
	// Format: email
	Email strfmt.Email `json:"email,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// status
	// Enum: [Active Inactive Deleted]
	Status string `json:"status,omitempty"`
}

// Validate validates this customer
func (m *Customer) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Customer) validateEmail(formats strfmt.Registry) error {

	if swag.IsZero(m.Email) { // not required
		return nil
	}

	if err := validate.FormatOf("email", "body", "email", m.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

var customerTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Active","Inactive","Deleted"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		customerTypeStatusPropEnum = append(customerTypeStatusPropEnum, v)
	}
}

const (

	// CustomerStatusActive captures enum value "Active"
	CustomerStatusActive string = "Active"

	// CustomerStatusInactive captures enum value "Inactive"
	CustomerStatusInactive string = "Inactive"

	// CustomerStatusDeleted captures enum value "Deleted"
	CustomerStatusDeleted string = "Deleted"
)

// prop value enum
func (m *Customer) validateStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, customerTypeStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Customer) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Customer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Customer) UnmarshalBinary(b []byte) error {
	var res Customer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
